language: cpp

compiler:
  - gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # C++14
 - sudo apt-get update -qq
 - sudo apt-get install qt5-default

install: 
  - sudo apt-get install -qq g++-5 # C++14

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

