language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:beineri/opt-qt591-xenial
  - sudo apt-get update -qq
 
install:
  - sudo apt-get install -qq g++-6 qt5-default
  - sudo apt-get --yes install qt59-meta-full
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

before_script:
  - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
  - source $QT_ENV_SCRIPT
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

    
